In [1]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

In [5]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [7]:
df.drop(columns = ['Serial No.'], inplace = True)

In [8]:
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76
2,316,104,3,3.0,3.5,8.00,1,0.72
3,322,110,3,3.5,2.5,8.67,1,0.80
4,314,103,2,2.0,3.0,8.21,0,0.65

In [9]:
X = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 42)

In [21]:
from sklearn.linear_model import LinearRegression , Ridge, Lasso
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

from sklearn.metrics import r2_score,mean_squared_error

In [28]:
models= {
    'linear regression':LinearRegression(),
    'svr':SVR(),
    'ridge':Ridge(),
    'lasso':Lasso(),
    'tree':DecisionTreeRegressor(),
    'random forest':RandomForestRegressor(),
    'xgboost':XGBRegressor()
}

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
results = []
for name, model in models.items():
    model.fit(X_train,y_train)
    pred = model.predict(X_test)

    r2 = r2_score(y_test,pred)
    mse = mean_squared_error(y_test,pred)

    results.append({
        'Model':name,
        'r2_score':r2,
        'MSE':mse
    })

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(by= 'r2_score', ascending=False )

In [31]:
results_df

               Model  r2_score       MSE
0  linear regression  0.818843  0.003705
2              ridge  0.818789  0.003706
5      random forest  0.791542  0.004263
1                svr  0.758938  0.004930
6            xgboost  0.746692  0.005180
4               tree  0.578435  0.008621
3              lasso -0.007248  0.020598